### ISSUE TITLE
Error while reading thumb.svm

### ISSUE THREAD

**Issue by abood91** [zmdsjtu/Hand_gesture#2]
Hello, 

Could you please upload all the .svm files and .data files again

the code keeps throwing 

```
terminate called after throwing an instance of 'dlib::serialization_error'
  what():  An error occurred while trying to read the first object from the file thumb.svm.
ERROR: No more objects were in the file!

Aborted (core dumped)
```

**Comment by YijiaZhao** [comment]
I meet the same problem 
erminate called after throwing an instance of 'dlib::serialization_error'
  what():  An error occurred while trying to read the first object from the file thumb.svm.
ERROR: No more objects were in the file!

**Comment by YijiaZhao** [comment]
@abood91 ,  the .svm file is ok, write the full path

**Comment by zmdsjtu** [comment]
@YijiaZhao Thanks. I will close the issue.
